name: dooit
description: "This is an app that gives you motivation for health and exercise."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  dotted_border: ^3.1.0

  # Tools
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

  # API
  http: ^1.4.0
  kakao_flutter_sdk_common: ^1.9.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/logo/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100

    - family: HSSanTokki
      fonts:
        - asset: assets/fonts/HSSantokki-Regular.ttf